function create_pyfnirs_mlinput_fixture(outputMatPath)
%CREATE_PYFNIRS_MLINPUT_FIXTURE Create a small genuine MATLAB table fixture.
%   The fixture is synthetic and must not be presented as research data. Its
%   Values table is deliberately out of sample/feature order and contains a
%   traceable invalid value.

if nargin ~= 1
    error('PYfNIRs:Arguments', 'Expected output MAT path.');
end
outputMatPath = char(string(outputMatPath));
if isfile(outputMatPath) || isfolder(outputMatPath)
    error('PYfNIRs:OutputExists', 'Refusing to overwrite fixture: %s', outputMatPath);
end
parent = fileparts(outputMatPath);
if ~isfolder(parent)
    mkdir(parent);
end

study = struct();
study.Kind = 'PYfNIRsDA.Study';
study.SchemaVersion = uint32(1);
study.Sources = table( ...
    ["SRC-A"; "SRC-B"], ...
    ["synthetic_sensor"; "synthetic_sensor"], ...
    [1; 1], ...
    ["SYNTHETIC://record-a.mat"; "SYNTHETIC://record-b.mat"], ...
    ["values/a"; "values/b"], ...
    ["SYNTHETIC-A"; "SYNTHETIC-B"], ...
    ["fixture"; "fixture"], ...
    ["direct"; "direct"], ...
    'VariableNames', {'SourceID', 'Kind', 'SchemaVersion', 'FilePath', ...
    'PayloadPath', 'Fingerprint', 'Adapter', 'Capability'});
study.Values = table( ...
    ["OBS-8"; "OBS-42"; "OBS-8"; "OBS-42"], ...
    ["F-HbR"; "F-O2"; "F-O2"; "F-HbR"], ...
    [NaN; 1.25; 2.5; 3.75], ...
    [false; true; true; true], ...
    ["qc_rejected"; ""; ""; ""], ...
    ["SRC-B"; "SRC-A"; "SRC-B"; "SRC-A"], ...
    'VariableNames', {'ObservationID', 'FeatureID', 'Value', 'IsValid', 'MissingReason', 'SourceID'});
study.FeatureDefinitions = table( ...
    ["F-O2"; "F-HbR"], ...
    ["synthetic_mean"; "synthetic_mean"], ...
    ["CH"; "CH"], ...
    ["HbO"; "HbR"], ...
    ["N1"; "N1"], ...
    [""; ""], ...
    [""; ""], ...
    [""; ""], ...
    [NaN; NaN], ...
    [NaN; NaN], ...
    [NaN; NaN], ...
    [NaN; NaN], ...
    [1; 1], ...
    ["a.u."; "a.u."], ...
    ["none"; "none"], ...
    ["scalar"; "scalar"], ...
    ["scalar"; "scalar"], ...
    ["SYNTHETIC-PARAM-A"; "SYNTHETIC-PARAM-B"], ...
    ["SYNTHETIC-MAP-A"; "SYNTHETIC-MAP-B"], ...
    'VariableNames', {'FeatureID', 'Metric', 'Level', 'Hemoglobin', ...
    'NodeA', 'NodeB', 'RoleA', 'RoleB', 'FrequencyLowHz', ...
    'FrequencyHighHz', 'WindowStartSeconds', 'WindowEndSeconds', ...
    'Scale', 'Unit', 'Transform', 'Direction', 'Dimension', ...
    'ParameterFingerprint', 'MappingFingerprint'});
study.Observations = table( ...
    ["OBS-42"; "OBS-8"; "OBS-PAIR-7"], ...
    ["REC-42"; "REC-8"; ""], ...
    ["SUB-42"; "SUB-8"; ""], ...
    [""; ""; "PO-7"], ...
    ["control"; "case"; ""], ...
    ["baseline"; "followup"; "paired"], ...
    ["S1"; "S2"; "S1"], ...
    ["T0"; "T1"; "T0-T1"], ...
    [true; true; true], ...
    ["SRC-A"; "SRC-B"; "SRC-A"], ...
    [31; 45; NaN], ...
    'VariableNames', {'ObservationID', 'RecordID', 'SubjectID', ...
    'PairObservationID', 'Group', 'Condition', 'Session', 'Timepoint', ...
    'Include', 'SourceID', 'Cov_AgeYears'});
study.PairLinks = table( ...
    "PO-7", "PAIR-7", "REC-42", "REC-8", "SUB-42", "SUB-8", ...
    "baseline", "followup", "paired", "S1", "T0-T1", ...
    'VariableNames', {'PairObservationID', 'PairID', 'RecordIDA', ...
    'RecordIDB', 'SubjectIDA', 'SubjectIDB', 'RoleA', 'RoleB', ...
    'Condition', 'Session', 'Timepoint'});
study.CovariateMetadata = table( ...
    "Cov_AgeYears", "subject", "synthetic_fixture", "SubjectID", ...
    'VariableNames', {'ColumnName', 'Level', 'Origin', 'DataKey'});
study.FixtureNotice = struct('Label', 'SYNTHETIC only; not research data', 'Seed', uint32(7));

save(outputMatPath, 'study', '-v7.3');

[~, baseName, extension] = fileparts(outputMatPath);
expected = struct();
expected.label = 'SYNTHETIC only; not research data';
expected.source_file_name = [baseName, extension];
expected.observation_ids = ["OBS-42"; "OBS-8"; "OBS-PAIR-7"];
expected.sample_ids = ["OBS-42"; "OBS-8"];
expected.feature_ids = ["F-O2"; "F-HbR"];
expected.matrix_value_text = ["1.25", "3.75"; "2.5", "NaN"];
expected.valid_mask = [true, true; true, false];
expected.missing_reasons = ["", ""; "", "qc_rejected"];
expected.targets = ["control"; "case"];
expected.age_years_text = ["31"; "45"];
expected.pair_observation_id = "PO-7";
expected.pair_id = "PAIR-7";
expected.pair_role_a = "baseline";
expected.pair_role_b = "followup";
expected.value_row_order = ["OBS-8/F-HbR"; "OBS-42/F-O2"; "OBS-8/F-O2"; "OBS-42/F-HbR"];
jsonPath = fullfile(parent, 'expected.json');
fid = fopen(jsonPath, 'w', 'n', 'UTF-8');
if fid < 0
    error('PYfNIRs:ExpectedOpenFailed', 'Cannot create expected values file: %s', jsonPath);
end
fileCleanup = onCleanup(@() fclose(fid));
fwrite(fid, jsonencode(expected), 'char');
fwrite(fid, newline, 'char');
clear fileCleanup;
end
